[package]
name = "wow-translate-dll"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
authors.workspace = true

[lib]
name = "wow_translate"
crate-type = ["cdylib"]

[dependencies]
wow-hook = { workspace = true }
wow-shared = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
